#gt915 touchpanel driver

EXTRA_CFLAGS +=-Wno-error=date-time
EXTRA_CFLAGS +=-Wno-date-time

obj-$(CONFIG_TOUCHSCREEN_GT9XX_MIDO)	+= gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_MIDO)	+= gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_MIDO)	+= goodix_tool.o
