ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
